version: "3"

services:
  os:
    build: ./os
    tty: true
    platform: linux/arm64
    volumes:
      - ./os/apps:/apps
    environment:
      TZ: Asia/Tokyo
    ports:
      - "9090:9090"
      - "3000:3000"
      - "5432:5432"
      - "3306:3306"
